epinio/docs

src/SUMMARY.md
src/developer/howtos/development.md
src/user/howtos/gitjob_push.md

This PR fixes the following things:
* double link in the summary (install_epinio_magicDNS.md)
* Subtitle **Behind the curtains** not interpreted
* one typo in **gitjob_push**

Fix some typos and links

---

book.toml

The current change will have all menu levels collapsed as the default behavior. What's the preferred default behavior? @agracey @jimmykarily?

Make navigation menu collapsible/expandable

---

src/explanations/advanced.md
src/explanations/configuration.md
src/howtos/certificate_issuers.md
src/howtos/gitjob_push.md
src/howtos/setup-external-registry.md
src/installation/install_epinio_customDNS.md
src/installation/install_epinio_magicDNS.md
src/installation/install_epinio_on_k3d.md
src/installation/install_epinio_on_k3s.md
src/installation/install_epinio_on_rancher_desktop.md

Removed all the `epinio install` references, and changed when appropriate with links or the `helm install` equivalent.

Removed the epinio install reference

---

src/SUMMARY.md
src/explanations/detailed-push-process.md
src/explanations/security.md

fix #34 
fix: some old references to the old (cli) installer.
removed: old behaviour not present in current helm-based system.

Removal of lingering references to the old installer

---

src/installation/install_epinio_cli.md

1. Fixed incorrect binaries names on epinio CLI install docs.

Fixed epinio CLI binaries extension name

---

src/SUMMARY.md
src/installation/installation.md

the new installation method with a single Helm chart has been added.
The previous "two methods" have been removed from the Summary. However the pages are kept for the time being, in case someone has a reference to it. They will/should be removed in the future.

Add new install method

---

src/SUMMARY.md
src/installation/install_epinio_cli.md
src/installation/install_epinio_customDNS.md
src/installation/install_epinio_magicDNS.md
src/installation/installation.md

Fixes #64
The overall links in the Installation section have been updated to reflect the new Docs structure.
The references to the previous two methods have been also updated to mention the new single installation method

Updated links for new structure

---

src/howtos/debug.md
src/howtos/howtos.md
src/howtos/port_forwarding.md

As stated in
- https://github.com/epinio/epinio/issues/601#issuecomment-1067899229  
at the moment we cannot customize the build phase, so it's not possible to enable the debug for the languages that needs a flag during build time.
This PR is just going to remove the debug from the port-forward page, to add a dedicated debug how-to.
- Ref: https://github.com/epinio/docs/issues/56

How to debug an app

---

src/SUMMARY.md

We forgot to add a link to the "how to debug an app" page in the nav bar.

Add link to debug page in nav bar

---

.github/workflows/updatecli.yml
src/installation/install_epinio_cli.md
updatecli/updatecli.d/installation.yaml

Fix #76 
While looking at the Epinio cli installation page, I noticed that the version was outdated and it seems to be a manual procedure to update it so I propose to automate the process 
Example of the updatecli manifest executed locally. Please not that I didn't update the url as I would like to test that updatecli can do it from Github Action 
```
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline "updatecli/updatecli.d/installation.yaml"
SCM repository retrieved: 0
++++++++++++
+ PIPELINE +
++++++++++++
#####################################################
#####################################################
SOURCES
=======
updatecli
---------
Searching for version matching pattern "latest"
✔ Github Release version "v0.6.1" found matching pattern "latest"
CHANGELOG:
---------- …
```

Automate downloard url using updatecli 

---

docs/howtos/create_custom_service.md
docs/howtos/install_epinio_on_public_cloud.md
docs/howtos/install_epinio_on_rancher_desktop.md
docs/howtos/install_wordpress_application.md
docs/installation/uninstall_epinio.md
versioned_docs/version-0.7.1/howtos/create_custom_service.md
versioned_docs/version-0.7.1/howtos/install_epinio_on_public_cloud.md
versioned_docs/version-0.7.1/howtos/install_epinio_on_rancher_desktop.md
versioned_docs/version-0.7.1/howtos/install_wordpress_application.md
versioned_docs/version-0.7.1/installation/uninstall_epinio.md

This PR tries to improve/fix 5 things in the doc:
1. Remove duplicate link for service page
2. Warn the user about deployment in the default workspace in case of uninstallation, fix #107 
3. Advertise service feature in the wordpress example
4. Remove `--values epinio-values.yaml` in Epinio installation on Rancher Desktop
5. If you want to use Epinio on AKS, you must use external registry, fix #104

Fix some doc issues

---

.github/workflows/updatecli.yml
updatecli/scripts/docusaurus.sh
updatecli/updatecli.d/installation.yaml

This PR adds an updatecli manifest to automatically run ` yarn run docusaurus docs:version x.y.z` if it detects a new version
Please note that I took the decision to reuse the same pipeline than the one that update installation url so we only have to review one PR after a new Epinio release. 
I also disabled the `automerge` pull request until we get confident in the process 
I tested that this change work by opening a fake version update on my fork on https://github.com/olblak/epinio-docs/pull/1
I didn't test the github action part

Automate docusaurus version update

---

.github/workflows/updatecli.yml

This pull request introduces the two following changes
* Switch updatecli Github Action to v2 relying on Javascript instead of docker
* Yarn/Npm installation workaround
During the last Epinio release, we noticed that we couldn't anymore install yarn using the GitHub Action `actions/setup-node`. It appeared to be a bug on that GitHub Action.
The second issue that we noticed was, Updatecli relied on a GitHub Action of type Docker. And due to that, the updatecli binary was in a isolated container and couldn't use the Docusaurus command. So we had to manually trigger the pipeline to finish the release. Updatecli Github Action is almost ready to have a v2 relying on Javascript
I used the command `act workflow_dispatch -j updatecli` to test that the workflow was working.
Also I had to comment …

Fix updatecli workflow for docusaurus version bump

---

docs/references/references.md
versioned_docs/version-0.8.0/references/references.md

Fixed missing authorization link in the `References` page.

Missing Authorization link

---

docs/references/cli/epinio_settings_show.md

Ref:
- https://github.com/epinio/epinio/pull/1499
---
Updated cli docs with the `--show-password` flag in the `epinio settings show` command.

Updated cli docs (--show-password flag)

---

docs/explanations/security.md
docs/howtos/gitjob_push.md
docs/howtos/install_epinio_on_rancher_desktop.md
docs/references/authorization.md
docs/references/cli/epinio_settings.md
docs/references/cli/epinio_settings_update-ca.md
docs/references/command_requirements.md
docs/references/commands.md
docs/references/settings.md
sidebars.js

Ref:
- https://github.com/epinio/epinio/issues/1361
---
The `epinio  settings update` command was replaced with the `epinio settings update-ca`.
All the references to the old command where moved to the `epinio login`.

Updated docs for hashed password

---

.github/workflows/updatecli.yml

The goal is to trigger an updatecli run as soon as Epinio release happen so we can bump all links

Trigger updatecli workflow on epinio release event

---

docs/tutorials/quickstart.md

The `epinio login`  command was missing from the quickstart.
It has been added in the "Push an application" section.

Added a login subsection to the quickstart

---

docs/howtos/install_epinio_on_eks.md

This PR fixes the following two issues:
- The how-to was missing from the sidebar
- The compact writing format was not easy to read
No rephrasing was done.

EKS how-to: updated sidebar and fixed doc linting

---

docusaurus.config.js

I noticed that footers links are referencing Docusaurus website, and instead I propose to mention Epinio related website.
* Stackoverflow, to encourage people to use the "epinio" tag
* Twitter to mention the rancherlabs account as we don't have an Epinio one
* Slack to mention the slack workspace, even thought I didn't test locally how it renders
\Signed-off-by: Olivier Vernin <olivier.vernin@suse.com>

Updating footer links

---

updatecli/updatecli.d/installation.yaml

The latest Updatecli version fix a long standing issue where semantic versioning "version filter" dropped the prefix "v"

fix: Updatecli manifest to correctly handle version with v prefix

---

docs/references/authentication_oidc.md
versioned_docs/version-1.3.0/references/authentication_oidc.md

Two changes:
* Move localhost ingress caution box from `next` to `1.3.0`. In `next` it is not relevant anymore as  https://github.com/epinio/epinio/pull/1787 has been implemented.
* Update `--prompt` description from `next` in `1.3.0`

Update OIDC in 1.3.0, remove localhost caution from next due PR#1787

---

docs/references/supported_applications.md
docs/tutorials/quickstart.md
versioned_docs/version-0.6.2/tutorials/quickstart.md
versioned_docs/version-0.7.1/tutorials/quickstart.md
versioned_docs/version-0.8.0/tutorials/quickstart.md
versioned_docs/version-0.9.0/tutorials/quickstart.md
versioned_docs/version-1.0.0/tutorials/quickstart.md
versioned_docs/version-1.1.0/tutorials/quickstart.md
versioned_docs/version-1.2.0/tutorials/quickstart.md
versioned_docs/version-1.3.0/references/supported_applications.md
versioned_docs/version-1.3.0/tutorials/quickstart.md

Added procfile, updated Paketo docs and fixed quickstart newline.
Fixes #183 
---
Here the page where we describe a bit more the Paketo Buildpacks: https://deploy-preview-186--epinio-docs-staging.netlify.app/references/supported_applications
I've seen it going through the doc at the [Quickstart](https://deploy-preview-186--epinio-docs-staging.netlify.app/tutorials/quickstart#push-an-app), so it should be visible enough.
I've updated it only in the current and v.1.3.0 doc though, should we go back also on older releases? Maybe from the 1.0.0.

Updated Paketo docs

---

docs/installation/install_epinio.md
versioned_docs/version-1.4.0/installation/install_epinio.md

Related to https://github.com/epinio/docs/issues/189
Adds a note on the Epinio installation page about the use of `epinio settings update-ca` that may be useful.

Extending epinio settings update-ca to epinio installation page

---

docs/installation/install_epinio.md

Ref. https://github.com/epinio/docs/issues/198
Sync docs with CI.
Tested manually on k3s with disabled "internal" traefik.
Note: Latest traefik requires helm=>3.9.0

Use latest traefik chart

---

updatecli/updatecli.d/installation.yaml

`Pullrequest` is deprecated in favor of `actions` [cfr](https://github.com/updatecli/updatecli/releases/tag/v0.40.0)

Update updatecli manifest to remove manifest syntax warning

---

docs/howtos/install_epinio_on_eks.md
docs/howtos/install_epinio_on_public_cloud.md

Ref. https://github.com/epinio/epinio/issues/2083
I updated the EKS docs and  removed things which confused me :)
I tested following on epinio devel v1.6.2+ with updated epinio CLI bin (missing cert for app exec):
* epinio deployed on EBS v1.23 (v1.24 tested by CI) with valid route53 domain zone, ELB and nginx-ingress, `letsencrypt-production` as tlsIssue (I removed the misleading `letsencrypt-epinio` part)
* epinio DEX UI login
* epinio login --oidc ...
* epinio push app ...
* epinio app exec

Update EKS documentation with additional requirements for v1.23+

---

docs/tutorials/single-dev-workflow.md

Right now, the example port-forward in the single-dev HowTo uses `epinio port-forward 8080:8080 mysimpleapp`, but it should be `epinio port-forward mysimpleapp 8080:8080`
I didn't know whether I should change the `versioned-docs` as well, just let me know and I'll update the PR.

Fix wrong port-forward syntax in single-dev example

---

docs/howtos/custom_builder.md
docs/tutorials/custom_builder_go.md
docs/tutorials/namespace-tutorial.md
docs/tutorials/single-dev-workflow.md

This PR moves the Gitea custom builder deploy HowTo to the Tutorials section, with a new title.

Moved Gitea custom builder how-to to tutorials

---

docs/tutorials/namespace-tutorial.md

The page had no Title set in docusaurus meta so the sidebar menu contained just an link with empty Title string.

Bring Namespaces title back

---

updatecli/updatecli.d/cert-manager.yaml

While looking at the documentation, I noticed the cert-manager installation link was really old.
This manifest will automatically track the latest version and open a PR
Tested locally 
<details><summary> local execution</summary>
```
>  updatecli diff --config updatecli/updatecli.d/cert-manager.yaml        
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline "updatecli/updatecli.d/cert-manager.yaml"
SCM repository retrieved: 1
++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++
++++++++++++
+ PIPELINE +
++++++++++++
###########################################################
###########################################################
SOURCES
=======
cert-manager
------------
Searching for version matching pattern "latest"
✔ GitHub release version "v1.12.3" found matching pattern …
```

Automate cert-manager update

---

docs/howtos/customization/create_git_configuration.md
docs/references/git_configuration.md

fix #305 
rewrite the gitconfig docs, use the gitconfig command instead of direct access to the cluster

chore: updated gitconfig documentation to use the new command ensemble

---

docs/references/authorization.md
versioned_docs/version-0.9.0/references/authorization.md
versioned_docs/version-1.0.0/references/authorization.md
versioned_docs/version-1.1.0/references/authorization.md
versioned_docs/version-1.10.0/references/authorization.md
versioned_docs/version-1.2.0/references/authorization.md
versioned_docs/version-1.3.0/references/authorization.md
versioned_docs/version-1.4.0/references/authorization.md
versioned_docs/version-1.5.0/references/authorization.md
versioned_docs/version-1.5.1/references/authorization.md
versioned_docs/version-1.5.2/references/authorization.md
versioned_docs/version-1.6.0/references/authorization.md
versioned_docs/version-1.6.1/references/authorization.md
versioned_docs/version-1.6.2/references/authorization.md
versioned_docs/version-1.7.0/references/authorization.md
versioned_docs/version-1.7.1/references/authorization.md
versioned_docs/version-1.8.0/references/authorization.md
versioned_docs/version-1.8.1/references/authorization.md
versioned_docs/version-1.9.0/references/authorization.md

Command was not working properly for a missing escape.
Fixed also in previous versioned docs.

Fixed missing escape for dollar sign in command

---

docs/howtos/use-develop/app_recover.md
docs/references/cert-manager.md

fix: missing reference to mandatory use of routing secrets when CM is disabled.
fix: double `that that` in app recovery.

Two small fixes in recent work.

---

docusaurus.config.js

Generate analytics under Google GA4, rather than the sunsetted UA. may provide useful data for future decisions.

Update google tag for GA4

---

docusaurus.config.js

Reverts epinio/docs#395.
It didn't seem to work. Some more investigation is needed.

Revert "Update google tag for GA4"

---

docs/howtos/other/certificate_issuers.md
docs/howtos/other/port_forwarding.md
docs/howtos/use-develop/app_recover.md
docs/installation/other_inst_scenarios/install_epinio_on_k3s.md
docs/installation/other_inst_scenarios/install_epinio_on_rke.md
docs/installation/wildcardDNS_setup.md
docs/references/authentication_oidc.md
docs/references/settings.md
versioned_docs/version-1.11.0/howtos/other/certificate_issuers.md
versioned_docs/version-1.11.0/howtos/other/port_forwarding.md
versioned_docs/version-1.11.0/howtos/use-develop/app_recover.md
versioned_docs/version-1.11.0/installation/other_inst_scenarios/install_epinio_on_k3s.md
versioned_docs/version-1.11.0/installation/other_inst_scenarios/install_epinio_on_rke.md
versioned_docs/version-1.11.0/installation/wildcardDNS_setup.md
versioned_docs/version-1.11.0/references/authentication_oidc.md
versioned_docs/version-1.11.0/references/settings.md

This removes howdoi.website as a suggested option. This is specific to the current version of the docs.

Remove howdoi.website (it no longer works)

---

docs/references/authorization.md

Adjust documentation so that the `:` delimiter is not just mentioned in passing but described at length and tied back to our OIDC authentication capabilities to automate such a role mapping to namespaces.

Highlight `:` delimiter capabilities

---

docs/howtos/operations/aws_iam_integration.md
docs/installation/install_epinio.md
docs/references/commands/cli/epinio_server.md

Due to issues with docusaurus not tagging proper versions, we need to back port some changes for 1.12,

Backport 1.12 Changes
