src/user/installation/install_epinio_on_rancher_desktop.md

Extracted from https://github.com/epinio/epinio/pull/847

Add Rancher Desktop tutorial

---

src/SUMMARY.md
src/installation/install_dependencies.md
src/installation/install_epinio_cli.md
src/installation/install_epinio_customDNS.md
src/introduction.md
src/references/references.md
src/references/supported-apps.md

- bring back sys requirements
- fix remaining user prefixes
- remove dependency file after including content in cli docs

Review userdocs

---

src/howtos/provision_external_ip_for_local_kubernetes.md

Signed-off-by: Klaus Kämpf <kkaempf@suse.de>

minikube metallb setup is covered in the installation section

---

src/explanations/advanced.md
src/installation/install_wordpress_application.md
src/references/supported-apps.md
src/tutorials/quickstart.md

Fixes https://github.com/epinio/epinio/issues/909

Adapt push cmd documentation to new design

---

src/references/cli/epinio_app_create.md
src/references/cli/epinio_app_update.md
src/references/cli/epinio_install.md
src/references/cli/epinio_namespace.md
src/references/cli/epinio_namespace_show.md
src/references/cli/epinio_push.md
src/references/cli/epinio_server.md
src/references/cli/epinio_service.md
src/references/cli/epinio_service_list.md

Updated the cli manpages to reflect the state of the v0.1.5 cli.

fix: Updated cli ref to cli v0.1.5 state

---

src/SUMMARY.md
src/explanations/advanced.md
src/explanations/detailed-push-process.md
src/explanations/epinio-push-detailed.svg
src/explanations/security.md
src/howtos/howtos.md
src/howtos/setup-external-registry.md
src/references/api.md
src/references/cli/epinio_install.md
src/references/cli/epinio_server.md
src/references/references.md

sibling PR: https://github.com/epinio/epinio/pull/974

Update cli docs

---

src/howtos/setup-external-s3.md

Fix #32
These are the instructions on how to configure S3 storage with Helm.

Doc how to configure S3 using Helm

---

src/installation/install_epinio_auto.md
src/installation/install_epinio_manual.md
src/installation/install_epinio_on_k3d.md
src/installation/installation.md
src/installation/system_requirements.md
src/tutorials/quickstart.md

This PR fixes #35 updating the troubleshooting section.
It also adds some minor navigation fixes (broken links) and fix some typos.

Troubleshooting update and minor fixes

---

src/installation/install_epinio_auto.md

Ref https://github.com/epinio/helm-charts/issues/56

fix: switch systemDomain to domain to match charts

---

src/installation/install_epinio_customDNS.md
src/installation/install_epinio_magicDNS.md

Add links to helm installation methods, otherwise we don't know how to install Epinio.

Fix installation with custom DNS

---

src/SUMMARY.md
src/installation/install_epinio_on_rancher.md

Add Epinio installation on Rancher

---

src/explanations/advanced.md
src/explanations/detailed-push-process.md
src/explanations/epinio-push-detailed.svg
src/installation/install_epinio_manual.md
src/installation/uninstall_epinio.md
src/references/epinio-push-simple.svg
src/references/supported-apps.md

fix: tekton references in text and graphics

---

src/SUMMARY.md
src/howtos/custom_routes.md

Document how to create custom routes for applications

---

src/introduction.md

Added links to external sites (Kubernetes, LinkerD and PaaS).
Added links to internal sites (Explanations and HowTos).
Added a Next steps section

Added links and Next step section

---

src/howtos/install_epinio_on_k3d.md
src/howtos/install_epinio_on_k3s.md
src/howtos/install_epinio_on_minikube.md
src/howtos/install_epinio_on_public_cloud.md
src/howtos/install_epinio_on_rancher.md
src/howtos/install_epinio_on_rancher_desktop.md
src/howtos/install_epinio_on_rke.md
src/howtos/install_wordpress_application.md
src/references/README.md
src/references/commands.md
src/references/settings.md
src/references/supported-apps.md

More documentation fixes

---

src/howtos/install_epinio_on_rancher.md

Give more details about which Helm settings to use for Traefik and cert-manager installation.

Improve Epinio on Rancher install part

---

src/howtos/install_epinio_on_k3d.md

Fix #78 
Installation process tested inside a VM: ✅

Fix k3d create cluster command inside a VM

---

.github/workflows/updatecli.yml

Remove updatecli value param

---

updatecli/updatecli.d/installation.yaml

Typo in the part that I couldn't test locally

Fix updatecli source name

---

src/installation/install_epinio_cli.md

Update homebrew custom tap installation

---

src/installation/installation.md

Fix https://github.com/epinio/epinio/issues/1216

Add nginx ingress documentation

---

src/SUMMARY.md
src/howtos/create_custom_service.md
src/references/cli/epinio.md
src/references/cli/epinio_app.md
src/references/cli/epinio_app_export.md
src/references/cli/epinio_service.md
src/references/cli/epinio_service_bind.md
src/references/cli/epinio_service_catalog.md
src/references/cli/epinio_service_create.md
src/references/cli/epinio_service_delete.md
src/references/cli/epinio_service_list.md
src/references/cli/epinio_service_show.md
src/references/services.md

Docs for https://github.com/epinio/epinio/issues/1332

Helm services

---

src/howtos/create_custom_service.md
src/references/cli/epinio_app_export.md
src/references/cli/epinio_service.md
src/references/cli/epinio_service_bind.md
src/references/cli/epinio_service_catalog.md
src/references/cli/epinio_service_create.md
src/references/cli/epinio_service_delete.md
src/references/cli/epinio_service_list.md
src/references/cli/epinio_service_show.md
src/references/services.md

This is a follow-up of PR #97
Rephrased to active voice and made spelling modifications.

Service pages update

---

docs/references/cli/epinio_service.md
docs/references/cli/epinio_service_catalog.md
docs/references/cli/epinio_service_create.md
docs/references/cli/epinio_service_list.md
docs/references/cli/epinio_service_show.md
docs/references/cli/epinio_service_unbind.md

Updating CLI docs for https://github.com/epinio/epinio/pull/1460
Waiting for merge

Update CLI docs for services

---

docs/references/authorization.md

ref: https://github.com/epinio/epinio/issues/1383

Clean up labels and domain usage

---

docs/howtos/create_custom_service.md

Part of: https://github.com/epinio/epinio/issues/1463

Add instruction on how to set a service icon

---

docs/references/authorization.md
docs/references/settings.md

to match changes here: https://github.com/epinio/epinio/pull/1522

Update docs for user's password

---

docs/howtos/install_epinio_on_rancher_desktop.md
versioned_docs/version-0.8.0/howtos/install_epinio_on_rancher_desktop.md

Fixes #110
This workaround is based on the main repo issues:
https://github.com/rancher-sandbox/rancher-desktop/issues/576

Added RancherDesktop unprivileged port workaround

---

docs/references/authorization.md

Part of : https://github.com/epinio/helm-charts/issues/214
Sibling PRs:
- https://github.com/epinio/epinio/pull/1539
- https://github.com/epinio/helm-charts/pull/217

Update docs about chart's default users

---

docs/howtos/install_metrics_server.md

Address comments in #141
Ref https://github.com/epinio/epinio/issues/1399

Address comments on metrics server howto

---

docs/howtos/custom_builder.md
versioned_docs/version-1.0.0/howtos/custom_builder.md

Relevant: https://github.com/epinio/epinio/pull/1617

Move docs on how to create custom builder from the epinio/epinio repo

---

docs/howtos/create_custom_appcharts.md
docs/howtos/create_custom_service.md
docs/howtos/custom_builder.md
docs/howtos/custom_routes.md
docs/howtos/install_epinio_on_k3d.md
docs/howtos/install_epinio_on_k3s.md
docs/howtos/install_epinio_on_minikube.md
docs/howtos/install_epinio_on_public_cloud.md
docs/howtos/install_epinio_on_rancher.md
docs/howtos/install_epinio_on_rancher_desktop.md
docs/howtos/install_epinio_on_rke.md
docs/howtos/install_metrics_server.md
docs/howtos/install_wordpress_application.md
docs/howtos/port_forwarding.md
docs/howtos/setup_routing_secrets.md
docs/howtos/using_custom_appcharts.md
docs/references/routing_secrets.md

HowTo and Reference for Routing Secrets

---

docs/references/cert-manager.md

Ref https://github.com/epinio/epinio/issues/1639
Ref https://github.com/epinio/epinio/pull/1654

Reference docs for Cert Manager component

---

docs/howtos/create_custom_appcharts.md
docs/references/customization/appcharts.md
docs/references/customization/routing_secrets.md

fix #151 
feat: extended app chart documentation, cross-link routing secrets
fix: moved routing secret ref into category `customizations`

Extended documentation of app charts

---

docs/howtos/create_custom_service.md
versioned_docs/version-1.1.0/howtos/create_custom_service.md

Added secret types annotation doc

Secret types annotation

---

docusaurus.config.js

Contextual search is set to true

Added Algolia search

---

package.json
yarn.lock

Updating the Docusaurus version from v2.0.0-beta.18 to v2.0.1

Updated Docusaurus to latest version 2.0.1

---

docs/versions.md
versioned_docs/version-0.8.0/versions.md
versioned_docs/version-0.9.0/versions.md
versioned_docs/version-1.0.0/versions.md
versioned_docs/version-1.1.0/versions.md

The "all versions" page is now updated to reflect the version selected.

Updated all versions page for all versions

---

docs/howtos/install_epinio_on_eks.md

Epinio installation on EKS does not exist yet.
Just create the first version.
Following the instructions you'll be able to get Epinio completely running on EKS with an ALB and WAF in front of it.

Install Epinio on EKS

---

updatecli/scripts/docusaurus.sh

Only execute the docausurus script in DRY_RUN mode

Only run docusaurus script in apply mode

---

docs/references/customization/catalog.md
versioned_docs/version-1.2.0/references/customization/catalog.md

Updating docs to add mongo db to catalog service

Adding mongo db to catalog service

---

docs/installation/install_epinio.md

Added EKS installation how to link on epinio install main page

Add EKS installation link

---

docs/howtos/install_wordpress_application.md
versioned_docs/version-1.3.0/howtos/install_wordpress_application.md

Fixes https://github.com/epinio/epinio/issues/1757

1757 fix wordpress docs

---

docs/references/authentication_oidc.md

By this PR adding a note about avoiding localhost for epinio dex endpoint. Also part with `--prompt` was modified to make a better sense. Feel free to rephrase.

Add notes for DEX

---

docs/references/commands/cli/app/epinio_app.md
docs/references/commands/cli/app/epinio_app_delete.md
docs/references/commands/cli/service/epinio_service.md
docs/references/commands/cli/service/epinio_service_delete.md
versioned_docs/version-1.4.0/installation/install_epinio_cli.md
versioned_docs/version-1.4.0/references/commands/cli/app/epinio_app.md
versioned_docs/version-1.4.0/references/commands/cli/app/epinio_app_delete.md
versioned_docs/version-1.4.0/references/commands/cli/service/epinio_service.md
versioned_docs/version-1.4.0/references/commands/cli/service/epinio_service_delete.md

Fix for wrong 1.3.0 ref and missing CLI docs in 1.4.0

Fix 1.4.0 docs

---

docs/references/authentication_oidc.md

Ref:
- https://github.com/epinio/epinio/pull/1816
- https://github.com/epinio/epinio/pull/1865
---
Documentation regarding the role mappings from the OIDC groups.

Claims and Role mappings documentation

---

docs/references/commands/cli/app/epinio_app_create.md
docs/references/commands/cli/app/epinio_app_update.md
docs/references/commands/cli/epinio_push.md
docs/references/commands/cli/epinio_server.md

Updating CLI docs with new flags/commands

Updating cli doc

---

docs/howtos/certificate_issuers.md
docs/howtos/contribute.md
docs/howtos/create_custom_appcharts.md
docs/howtos/create_custom_service.md
docs/howtos/custom_builder.md
docs/howtos/custom_routes.md
docs/howtos/debug.md
docs/howtos/gitjob_push.md
docs/howtos/install_epinio_on_eks.md
docs/howtos/install_epinio_on_k3d.md
docs/howtos/install_epinio_on_k3s.md
docs/howtos/install_epinio_on_minikube.md
docs/howtos/install_epinio_on_public_cloud.md
docs/howtos/install_epinio_on_rancher.md
docs/howtos/install_epinio_on_rancher_desktop.md
docs/howtos/install_epinio_on_rke.md
docs/howtos/install_metrics_server.md
docs/howtos/install_wordpress_application.md
docs/howtos/minio.md
docs/howtos/port_forwarding.md
docs/howtos/provision_external_ip_for_local_kubernetes.md
docs/howtos/setup_external_registry.md
docs/howtos/setup_external_s3.md
docs/howtos/setup_routing_secrets.md
docs/howtos/using_custom_appcharts.md

Fix https://github.com/epinio/epinio/issues/1898
feat: contribution how to - copy of the contribute document in the epinio repo
chore: shifted side bar positions
tweak: other titles for more consistent phrasing and capitalization

Added Contribution How To

---

docs/howtos/install_epinio_on_minikube.md
versioned_docs/version-1.6.0/howtos/install_epinio_on_minikube.md

Fixes https://github.com/epinio/docs/issues/204

Adding comment on minikube about enabling metric pod

---

versioned_docs/version-1.6.1/howtos/install_epinio_on_minikube.md

Updating metrics-server adddon description specifically for epinio version v1.6.1

Updating minikube metrics server addon doc in 1.6.1

---

docs/howtos/install_epinio_on_eks.md
docs/installation/install_epinio.md
versioned_docs/version-0.6.2/installation/installation.md
versioned_docs/version-0.7.1/installation/installation.md
versioned_docs/version-0.8.0/installation/install_epinio.md
versioned_docs/version-0.9.0/installation/install_epinio.md
versioned_docs/version-1.0.0/installation/install_epinio.md
versioned_docs/version-1.1.0/installation/install_epinio.md
versioned_docs/version-1.2.0/howtos/install_epinio_on_eks.md
versioned_docs/version-1.2.0/installation/install_epinio.md
versioned_docs/version-1.3.0/howtos/install_epinio_on_eks.md
versioned_docs/version-1.3.0/installation/install_epinio.md
versioned_docs/version-1.4.0/howtos/install_epinio_on_eks.md
versioned_docs/version-1.4.0/installation/install_epinio.md
versioned_docs/version-1.5.0/howtos/install_epinio_on_eks.md
versioned_docs/version-1.5.0/installation/install_epinio.md
versioned_docs/version-1.5.1/howtos/install_epinio_on_eks.md
versioned_docs/version-1.5.1/installation/install_epinio.md
versioned_docs/version-1.5.2/howtos/install_epinio_on_eks.md
versioned_docs/version-1.5.2/installation/install_epinio.md
versioned_docs/version-1.6.0/howtos/install_epinio_on_eks.md
versioned_docs/version-1.6.0/installation/install_epinio.md
versioned_docs/version-1.6.1/howtos/install_epinio_on_eks.md
versioned_docs/version-1.6.1/installation/install_epinio.md

extraArgs:
- --enable-certificate-owner-ref=true

Passing the array value to helm install

---

docs/howtos/certificate_issuers.md

Ticket ref https://github.com/epinio/helm-charts/issues/348
Chart PR ref https://github.com/epinio/helm-charts/pull/370
Main PR ref https://github.com/epinio/epinio/pull/2088

Document the `tlsIssuerMail` helm template variable.

---

docs/howtos/create_custom_appcharts.md
docs/howtos/create_custom_service.md
docs/howtos/custom_builder.md
docs/howtos/custom_routes.md
docs/howtos/install_epinio_on_eks.md
docs/howtos/install_epinio_on_k3d.md
docs/howtos/install_epinio_on_k3s.md
docs/howtos/install_epinio_on_minikube.md
docs/howtos/install_epinio_on_public_cloud.md
docs/howtos/install_epinio_on_rancher.md
docs/howtos/install_epinio_on_rancher_desktop.md
docs/howtos/install_epinio_on_rke.md
docs/howtos/install_metrics_server.md
docs/howtos/install_wordpress_application.md
docs/howtos/minio.md
docs/howtos/port_forwarding.md
docs/howtos/separate_workload_ingress.md
docs/howtos/setup_routing_secrets.md
docs/howtos/using_custom_appcharts.md

how to separate app ingress from api ingress

---

docs/howtos/aws_iam_integration.md

Implements: https://github.com/epinio/docs/issues/222
- Adding deletion process for policies
- Highlights the use of flag `--set server.stagingServiceAccountName=epinio-staging-service-account`
- Adds a mention to install Epinio as first step in the SA case.

Adding Policies deletion steps and other enhancements

---

docs/howtos/create_custom_appcharts.md
docs/howtos/using_custom_appcharts.md
docs/references/customization/appcharts.md
docs/references/manifests.md
versioned_docs/version-0.6.2/references/manifests.md
versioned_docs/version-0.7.1/references/manifests.md
versioned_docs/version-0.8.0/references/manifests.md
versioned_docs/version-0.9.0/references/manifests.md
versioned_docs/version-1.0.0/references/manifests.md
versioned_docs/version-1.1.0/references/manifests.md
versioned_docs/version-1.2.0/references/manifests.md
versioned_docs/version-1.3.0/references/manifests.md
versioned_docs/version-1.4.0/references/manifests.md
versioned_docs/version-1.5.0/references/manifests.md
versioned_docs/version-1.5.1/references/manifests.md
versioned_docs/version-1.5.2/references/manifests.md
versioned_docs/version-1.6.0/references/manifests.md
versioned_docs/version-1.6.1/references/manifests.md
versioned_docs/version-1.6.2/references/manifests.md
versioned_docs/version-1.7.0/references/manifests.md

Documentation of user-settable configuration values
Extended documents:
- creation of app chart
- usage of app chart
- app chart API (expectations of epinio)

Document configuration values for custom app charts

---

docs/howtos/aws_iam_integration.md
docs/howtos/create_custom_appcharts.md
docs/howtos/create_custom_service.md
docs/howtos/custom_builder.md
docs/howtos/custom_routes.md
docs/howtos/debug.md
docs/howtos/gitjob_push.md
docs/howtos/install_epinio_on_eks.md
docs/howtos/install_epinio_on_k3d.md
docs/howtos/install_epinio_on_k3s.md
docs/howtos/install_epinio_on_minikube.md
docs/howtos/install_epinio_on_public_cloud.md
docs/howtos/install_epinio_on_rancher.md
docs/howtos/install_epinio_on_rancher_desktop.md
docs/howtos/install_epinio_on_rke.md
docs/howtos/install_metrics_server.md
docs/howtos/install_wordpress_application.md
docs/howtos/minio.md
docs/howtos/namespaces.md
docs/howtos/port_forwarding.md
docs/howtos/provision_external_ip_for_local_kubernetes.md
docs/howtos/separate_workload_ingress.md
docs/howtos/setup_external_registry.md
docs/howtos/setup_external_s3.md
docs/howtos/setup_routing_secrets.md
docs/howtos/using_custom_appcharts.md
docs/references/api.md
docs/references/namespaces.md

Fix: #148 
Ref: https://github.com/epinio/epinio/issues/1635

Namespaces, reference and howto

---

docs/howtos/separate_workload_ingress.md

Ref. https://github.com/epinio/docs/issues/229

Custom domain for separate application ingress

---

docs/howtos/custom_builder.md
docs/howtos/custom_builder_go.md

Fixes: https://github.com/epinio/epinio/issues/2110

Added custom builder Gitea example

---

docs/howtos/install_epinio_on_eks.md
docs/howtos/install_epinio_on_k3d.md
docs/howtos/install_epinio_on_k3s.md
docs/howtos/install_epinio_on_public_cloud.md
docs/howtos/install_epinio_on_rancher_desktop.md
docs/howtos/install_epinio_on_rke.md
docs/howtos/minio.md
docs/installation/dns_setup.md
docs/installation/install_epinio.md
docs/installation/wildcardDNS_setup.md
docs/references/system_requirements/global.md
docs/tutorials/quickstart.md
src/SUMMARY.md

Redo: Quickstart, Install Epinio, Install on RKE2 and System requirements

---

docs/howtos/setup_external_registry.md

Ref https://github.com/epinio/helm-charts/issues/436

feat: explain cert usage for secured external registries

---

docs/howtos/create_custom_service.md

Ref https://github.com/epinio/epinio/issues/1633
See also
- https://github.com/epinio/epinio/pull/2389
- https://github.com/epinio/helm-charts/pull/441
- https://github.com/epinio/application/pull/13

Document custom values for service charts

---

docusaurus.config.js

Fixes #247.
Helps with branding/SEO per feedback from web team.

Add backlink to www.rancher.com

---

docs/howtos/gitjob_push.md

Updtating https://docs.epinio.io/howtos/gitjob_push according to https://github.com/epinio/docs/issues/251
- Explicitly mentioning to install Epinio, deploy and target a namespace
- Updating changes in service account yaml
- Updating info in `12factor-gitjob.yaml`

Updating gitjob info

---

docs/howtos/create_git_configuration.md
docs/references/git_configuration.md

This PR adds the documentation for the Git Configurations. See https://github.com/epinio/epinio/pull/2503

Added Git Configuration docs

---

docs/howtos/using_custom_service_values.md

ref https://github.com/epinio/epinio/pull/2485
Documentation for the more complex forms of custom values for services, now that thy are supported

explain usage of custom values for services in more detail

---

updatecli/updatecli.d/cert-manager.yaml

This pullrequest https://github.com/epinio/docs/pull/257/files moved two monitored files which broken the updatecli pipeline

Fix updatecli monitored file

---

docs/intro.md

I need a little help making sure the last two features are properly explained. So, WiP.

A little rewording. 

---

docs/references/commands/cli/epinio.md
docs/references/commands/cli/epinio_client-sync.md
docs/references/commands/cli/epinio_completion.md
docs/references/commands/cli/epinio_info.md
docs/references/commands/cli/epinio_login.md
docs/references/commands/cli/epinio_logout.md
docs/references/commands/cli/epinio_push.md
docs/references/commands/cli/epinio_server.md
docs/references/commands/cli/epinio_target.md
docs/references/commands/cli/epinio_version.md

ref. https://github.com/epinio/epinio/issues/2292

Update trace flags in references

---

docs/installation/install_epinio.md

A few points, marked with TODO: need a closer look.

Installation docs. First pass review and changes. 

---

docs/installation/install_epinio_cli.md

epinio CLI install - Refresh, typos, etc.

---

docs/installation/dns_setup.md

There are 3 TODOs which need clarification/I need help on.

DNS setup - Changes to improve readability.

---

docs/intro.md
docusaurus.config.js

A link to SUSE, as well as rancher in the Navbar.
Statement that Epinio is a SUSE project.
Ideas based on the 1000 points of light stuff from the ECM all-hands on 31/08/2023.

A very small step to improve our SUSE integration.

---

docs/installation/uninstall_epinio.md

Refresh uninstallation.

---

docs/howtos/other/certificate_issuers.md

Updated doc for https://github.com/epinio/helm-charts/pull/495

Updated docs for now optional `letsencrypt-production` ClusterIssuer

---

docs/installation/other_inst_scenarios/install_epinio_on_rancher.md

There are some TODOs requiring attention before the is ready to merge.

Refresh install/other/rancher.

---

docs/installation/other_inst_scenarios/install_epinio_on_rancher_desktop.md

Needs some technical review and work through.
Version numbers mentioned are old. Need updating. Does the technical content still apply?, etc.
RD has a push-button Epinio install which works, kinda.

Refresh Rancher Desktop install of Epinio

---

docs/howtos/customization/export_to_oci_registries.md
docs/howtos/customization/setup_export_registry.md
docs/references/commands/cli/app/epinio_app.md
docs/references/commands/cli/app/epinio_app_export.md
docs/references/commands/cli/configuration/epinio_configuration_update.md
docs/references/commands/cli/epinio.md
docs/references/commands/cli/epinio_export-registries.md
docs/references/commands/cli/namespace/epinio_namespace_list.md
docs/references/commands/cli/namespace/epinio_namespace_show.md
docs/references/commands/cli/service/epinio_service.md
docs/references/commands/cli/service/epinio_service_update.md
docs/references/commands/cli/settings/epinio_settings_update-ca.md
docs/references/customization/export_registries.md

Ref: https://github.com/epinio/epinio/issues/1770
Ref: https://github.com/epinio/epinio/pull/2509
- updated cli references for export to OCI registry, and other changes
- todo: export registry description

Explanations for export registries

---

docs/installation/other_inst_scenarios/install_epinio_on_k3s.md

minor refresh of other-inst/k3s

---

docs/installation/other_inst_scenarios/install_epinio_on_eks.md

Refresh other-inst/eks installation.

---

docs/installation/other_inst_scenarios/install_epinio_on_public_cloud.md

Removed the use of detail expandable. Those sections are too short to justify it and it breaks navigation from the sidebar to have headings inside the <detail>.
closes #293

Refresh other-inst/public-cloud.

---

docs/installation/install_epinio.md

Added disclaimer about risks involved with using s3gw for s3 storage

---

.github/workflows/deploy.yml
.github/workflows/updatecli.yml

Started failures of build:
https://github.com/epinio/docs/actions/runs/6042957092
https://github.com/epinio/docs/actions/runs/6043376789

Bumping node version to 18.x

---

docs/intro.md

And to test a production merge in Netlify.

Some minor typo and language fixes for introduction.

---

docs/tutorials/single-dev-workflow.md

I need help clarifying one paragraph/note. There is a TODO:.
Will close #321 when complete.

Refresh single developer workflow docs.

---

docusaurus.config.js

Ready for review and merge.
Rancher/SUSE integration stuff.

Revised Header and Footer

---

docs/tutorials/custom_builder_go.md

Refresh complex application tutorial.

---

docs/references/customization/staging-scripts.md
docs/references/customization/staging.md

Ticket https://github.com/epinio/epinio/issues/2153
Chart PR https://github.com/epinio/helm-charts/pull/502
Epinio PR https://github.com/epinio/epinio/pull/2659

Document staging scripts (reference)

---

docs/howtos/contribute.md

Refresh language in the how to contribute doc.

---

docs/howtos/operations/aws_iam_integration.md
docs/howtos/operations/install_metrics_server.md

Will close #346 and #347 when merged.

Refresh of the how-tos on AWS IAM and metrics server.

---

docs/howtos/customization/create_custom_role.md
docs/references/authentication_oidc.md
docs/references/authorization.md

Update of the documentation matching the new Authorization Roles:
See: https://github.com/epinio/epinio/issues/2631
- ADR: https://github.com/epinio/epinio/pull/2677
- Epinio: https://github.com/epinio/epinio/pull/2656
- Charts: https://github.com/epinio/helm-charts/pull/506

Added new Authorization Roles

---

docs/howtos/customization/create_custom_appcharts.md
docs/howtos/customization/create_custom_role.md
docs/howtos/customization/create_custom_service.md
docs/howtos/customization/create_git_configuration.md
docs/howtos/customization/custom_builder.md
docs/howtos/customization/custom_routes.md
docs/howtos/customization/export_to_oci_registries.md
docs/howtos/customization/provision_external_ip_for_local_kubernetes.md
docs/howtos/customization/setup_export_registry.md
docs/howtos/customization/setup_external_registry.md
docs/howtos/customization/setup_external_s3.md
docs/howtos/customization/setup_routing_secrets.md
docs/howtos/customization/using_custom_service_values.md
src/css/custom.css

All the shorter customization how-to documents.

---

docs/howtos/customization/create_custom_role.md
docs/howtos/customization/custom_routes.md
docs/howtos/customization/export_to_oci_registries.md
docs/howtos/customization/provision_external_ip_for_local_kubernetes.md
docs/howtos/customization/setup_export_registry.md
docs/howtos/customization/setup_external_registry.md
docs/howtos/customization/setup_external_s3.md

Should have been in #373. Hmmmph.

Unsaved changes to frontmatter, now in this commit.

---

docs/howtos/customization/create_custom_role.md

fix https://github.com/epinio/epinio/issues/2706

Added missing note about server restart after creating new roles, and rephrased to active voice

---

docs/references/customization/staging-scripts.md

ref https://github.com/epinio/epinio/issues/2715
ref https://github.com/epinio/epinio/pull/2717

Document the new `env` key for staging script specs.

---

docs/howtos/use-develop/app_recover.md

how to recover from a CRD deletion mishap

---

docs/references/cert-manager.md

fix #376 
see also https://github.com/epinio/epinio/pull/2681

Document epinio operation without cert-manager.

---

updatecli/updatecli.d/installation.yaml

* Enable automerge
* Use mutli line regular expression
* Add swagger url to update
* Add missing information to update

fix epinio installation update pipeline

---

docs/intro.md
docusaurus.config.js
versioned_docs/version-1.12.0/intro.md
versioned_docs/version-1.13.0/intro.md

This clarifies maintainership of the project.

Update maintainer statement
